import type { Material } from "../../../../domain/constants/materials.js";

export const algorithmsMaterials: (Material & { areaId: string })[] = [
  {
    areaId: "algorithms",
    title: "Introduction to Algorithms (CLRS)",
    author: "Cormen et al.",
    url: "https://mitpress.mit.edu/9780262046305/introduction-to-algorithms/",
    type: "book",
    desc: "The algorithm bible — proof-based coverage of sorting, graphs, dynamic programming, NP-completeness.",
  },
  {
    areaId: "algorithms",
    title: "The Algorithm Design Manual",
    author: "Steven Skiena",
    url: "https://www.algorist.com",
    type: "book",
    desc: "Part textbook, part encyclopedia — 75 algorithmic war stories and a catalog of 150+ algorithms.",
  },
  {
    areaId: "algorithms",
    title: "Neetcode 150",
    url: "https://neetcode.io/practice",
    type: "tool",
    free: true,
    desc: "Curated 150 LeetCode problems grouped by pattern — with video explanations for each solution.",
  },
  {
    areaId: "algorithms",
    title: "CS50x — Harvard",
    url: "https://cs50.harvard.edu/x/",
    type: "course",
    free: true,
    desc: "World's largest CS course — algorithms, data structures, memory, and problem solving from scratch.",
  },
  {
    areaId: "algorithms",
    title: "Algorithms, Part I — Princeton",
    url: "https://www.coursera.org/learn/algorithms-part1",
    type: "course",
    free: true,
    desc: "Union-find, sorting, priority queues, and symbol tables with Java — by Sedgewick & Wayne.",
  },
  {
    areaId: "algorithms",
    title: "Algorithms, Part II — Princeton",
    url: "https://www.coursera.org/learn/algorithms-part2",
    type: "course",
    free: true,
    desc: "Graphs, minimum spanning trees, shortest paths, tries, and compression — continuation of Part I.",
  },
  {
    areaId: "algorithms",
    title: "LeetCode",
    url: "https://leetcode.com",
    type: "tool",
    desc: "The industry-standard platform for practicing algorithmic problems — 3000+ problems with editorial.",
  },
  {
    areaId: "algorithms",
    title: "Visualgo",
    url: "https://visualgo.net",
    type: "tool",
    free: true,
    desc: "Interactive algorithm and data structure visualizations — BST, heap, graph traversal, sorting.",
  },
  {
    areaId: "algorithms",
    title: "Big-O Cheat Sheet",
    url: "https://www.bigocheatsheet.com",
    type: "docs",
    free: true,
    desc: "Quick reference for time and space complexities of common data structures and algorithms.",
  },
  {
    areaId: "algorithms",
    title: "Grokking Algorithms",
    author: "Aditya Bhargava",
    url: "https://www.manning.com/books/grokking-algorithms",
    type: "book",
    desc: "Visually illustrated introduction to algorithms — binary search, graphs, dynamic programming, k-NN.",
  },
];
