import type { Material } from "../../../../domain/constants/materials.js";

export const architectureMaterials: (Material & { areaId: string })[] = [
  {
    areaId: "architecture",
    title: "Clean Architecture",
    author: "Robert C. Martin",
    url: "https://www.oreilly.com/library/view/clean-architecture/9780134494272/",
    type: "book",
    desc: "Boundaries, use cases, and the dependency rule — the canonical guide to layered software architecture.",
  },
  {
    areaId: "architecture",
    title: "Patterns of Enterprise Application Architecture",
    author: "Martin Fowler",
    url: "https://martinfowler.com/books/eaa.html",
    type: "book",
    desc: "The catalog of enterprise patterns: Active Record, Repository, Service Layer, CQRS, and more.",
  },
  {
    areaId: "architecture",
    title: "Software Architecture: The Hard Parts",
    author: "Ford, Richards, Sadalage, Dehghani",
    url: "https://architecturethehardparts.com",
    type: "book",
    desc: "Trade-off analysis for distributed architectures — decomposition, data ownership, sagas.",
  },
  {
    areaId: "architecture",
    title: "Fundamentals of Software Architecture",
    author: "Ford & Richards",
    url: "https://fundamentalsofsoftwarearchitecture.com",
    type: "book",
    desc: "Architectural thinking, styles, characteristics, and decision-making for practitioners.",
  },
  {
    areaId: "architecture",
    title: "Martin Fowler — Architecture",
    url: "https://martinfowler.com/architecture/",
    type: "docs",
    free: true,
    desc: "Articles on hexagonal architecture, event sourcing, CQRS, microservices, and more.",
  },
  {
    areaId: "architecture",
    title: "System Design Primer",
    url: "https://github.com/donnemartin/system-design-primer",
    type: "docs",
    free: true,
    desc: "Large-scale system design — load balancers, caches, CDN, CAP theorem, sharding.",
  },
  {
    areaId: "architecture",
    title: "Architectural Katas",
    url: "https://nealford.com/katas/",
    type: "tool",
    free: true,
    desc: "Practice architectural thinking with open-ended design challenges used at conferences.",
  },
  {
    areaId: "architecture",
    title: "Building Microservices",
    author: "Sam Newman",
    url: "https://samnewman.io/books/building_microservices_2nd_edition/",
    type: "book",
    desc: "Decomposing monoliths, service boundaries, inter-service communication, and resilience.",
  },
  {
    areaId: "architecture",
    title: "Domain-Driven Design",
    author: "Eric Evans",
    url: "https://www.domainlanguage.com/ddd/",
    type: "book",
    desc: "The original DDD book — ubiquitous language, bounded contexts, aggregates, and domain events.",
  },
  {
    areaId: "architecture",
    title: "Implementing DDD",
    author: "Vaughn Vernon",
    url: "https://vaughnvernon.com/?page_id=168",
    type: "book",
    desc: "Hands-on DDD — aggregates, repositories, domain services, and event-driven design.",
  },
];
