import type { Material } from "../../../../domain/constants/materials.js";

export const cleanCodeMaterials: (Material & { areaId: string })[] = [
  {
    areaId: "clean-code",
    title: "Clean Code",
    author: "Robert C. Martin",
    url: "https://www.oreilly.com/library/view/clean-code-a/9780136083238/",
    type: "book",
    desc: "Timeless guide on naming, small functions, comments, error handling, and code boundaries.",
  },
  {
    areaId: "clean-code",
    title: "The Pragmatic Programmer",
    author: "Hunt & Thomas",
    url: "https://pragprog.com/titles/tpp20/",
    type: "book",
    desc: "DRY principle, tracer bullets, broken windows, code generation, and pragmatic philosophy.",
  },
  {
    areaId: "clean-code",
    title: "Refactoring",
    author: "Martin Fowler",
    url: "https://refactoring.com",
    type: "book",
    desc: "How to safely restructure existing code — catalog of 60+ named refactoring techniques.",
  },
  {
    areaId: "clean-code",
    title: "A Philosophy of Software Design",
    author: "John Ousterhout",
    url: "https://web.stanford.edu/~ouster/cgi-bin/book.php",
    type: "book",
    desc: "Deep module design, information hiding, comment-driven design, and managing complexity.",
  },
  {
    areaId: "clean-code",
    title: "Code Complete",
    author: "Steve McConnell",
    url: "https://www.microsoftpressstore.com/store/code-complete-9780735619678",
    type: "book",
    desc: "900-page encyclopedia of software construction — the most comprehensive code quality reference.",
  },
  {
    areaId: "clean-code",
    title: "Working Effectively with Legacy Code",
    author: "Michael Feathers",
    url: "https://www.oreilly.com/library/view/working-effectively-with/0131177052/",
    type: "book",
    desc: "Techniques for safely modifying untested code — seam points, characterization tests, and incremental improvement.",
  },
  {
    areaId: "clean-code",
    title: "SonarQube",
    url: "https://www.sonarsource.com/products/sonarqube/",
    type: "tool",
    desc: "Static analysis platform that detects code smells, bugs, and security vulnerabilities across 30+ languages.",
  },
  {
    areaId: "clean-code",
    title: "ESLint Docs",
    url: "https://eslint.org/docs/latest/",
    type: "docs",
    free: true,
    desc: "The standard JavaScript/TypeScript linter — enforce code quality rules across your team.",
  },
  {
    areaId: "clean-code",
    title: "Conventional Commits",
    url: "https://www.conventionalcommits.org",
    type: "docs",
    free: true,
    desc: "A specification for human and machine-readable commit messages — enables changelogs and semantic versioning.",
  },
];
