import type { Material } from "../../../../domain/constants/materials.js";

export const designSystemsMaterials: (Material & { areaId: string })[] = [
  {
    areaId: "design-systems",
    title: "Atomic Design",
    author: "Brad Frost",
    url: "https://atomicdesign.bradfrost.com",
    type: "book",
    free: true,
    desc: "The foundational methodology for building component hierarchies — atoms, molecules, organisms, templates, pages.",
  },
  {
    areaId: "design-systems",
    title: "Design Systems Handbook",
    author: "InVision",
    url: "https://www.designbetter.co/design-systems-handbook",
    type: "book",
    free: true,
    desc: "Building and scaling design systems — governance, tokens, documentation, and adoption.",
  },
  {
    areaId: "design-systems",
    title: "Storybook Docs",
    url: "https://storybook.js.org/docs",
    type: "docs",
    free: true,
    desc: "The industry-standard tool for building, documenting, and testing UI components in isolation.",
  },
  {
    areaId: "design-systems",
    title: "Radix UI Docs",
    url: "https://www.radix-ui.com/primitives",
    type: "docs",
    free: true,
    desc: "Accessible, unstyled component primitives — the correct foundation for any design system.",
  },
  {
    areaId: "design-systems",
    title: "Tailwind CSS Docs",
    url: "https://tailwindcss.com/docs",
    type: "docs",
    free: true,
    desc: "Utility-first CSS — design tokens as classes, responsive, dark mode, and theming.",
  },
  {
    areaId: "design-systems",
    title: "Style Dictionary",
    url: "https://styledictionary.com",
    type: "tool",
    free: true,
    desc: "Amazon's design token management tool — transforms tokens into any platform format.",
  },
  {
    areaId: "design-systems",
    title: "shadcn/ui",
    url: "https://ui.shadcn.com",
    type: "tool",
    free: true,
    desc: "Copy-paste accessible components built on Radix and Tailwind — owned by your codebase.",
  },
  {
    areaId: "design-systems",
    title: "Design Tokens Community Group",
    url: "https://design-tokens.github.io/community-group/",
    type: "docs",
    free: true,
    desc: "W3C community specification for design token formats — the standard for cross-tool token sharing.",
  },
  {
    areaId: "design-systems",
    title: "Shopify Polaris",
    url: "https://polaris.shopify.com",
    type: "docs",
    free: true,
    desc: "One of the most thorough public design system docs — principles, patterns, and component guidelines.",
  },
  {
    areaId: "design-systems",
    title: "Supernova",
    url: "https://supernova.io",
    type: "tool",
    desc: "Design system management platform — syncs tokens from Figma, generates docs and code.",
  },
];
