import type { Material } from "../../../../domain/constants/materials.js";

export const frontendMaterials: (Material & { areaId: string })[] = [
  {
    areaId: "frontend",
    title: "javascript.info",
    url: "https://javascript.info",
    type: "docs",
    free: true,
    desc: "The most complete, modern JS tutorial — from basics to advanced topics.",
  },
  {
    areaId: "frontend",
    title: "You Don't Know JS",
    author: "Kyle Simpson",
    url: "https://github.com/getify/You-Dont-Know-JS",
    type: "book",
    free: true,
    desc: "Deep-dive series on JavaScript internals — scope, closures, async, and more.",
  },
  {
    areaId: "frontend",
    title: "web.dev",
    url: "https://web.dev",
    type: "docs",
    free: true,
    desc: "Google's authoritative resource for web performance, accessibility, and PWAs.",
  },
  {
    areaId: "frontend",
    title: "React Official Docs",
    url: "https://react.dev",
    type: "docs",
    free: true,
    desc: "The new React docs — Hooks, Server Components, and all modern patterns.",
  },
  {
    areaId: "frontend",
    title: "CSS for JS Developers",
    author: "Josh Comeau",
    url: "https://css-for-js.dev",
    type: "course",
    desc: "Interactive course that truly explains how CSS works — transforms, layout, animations.",
  },
  {
    areaId: "frontend",
    title: "Frontend Masters",
    url: "https://frontendmasters.com",
    type: "course",
    desc: "Expert-taught courses on React, TypeScript, performance, and architecture.",
  },
  {
    areaId: "frontend",
    title: "The Odin Project",
    url: "https://www.theodinproject.com",
    type: "course",
    free: true,
    desc: "Full-stack curriculum with projects — HTML, CSS, JS, React, Node.",
  },
  {
    areaId: "frontend",
    title: "Eloquent JavaScript",
    author: "Marijn Haverbeke",
    url: "https://eloquentjavascript.net",
    type: "book",
    free: true,
    desc: "Timeless book covering JS fundamentals through data structures and async.",
  },
  {
    areaId: "frontend",
    title: "TypeScript Handbook",
    url: "https://www.typescriptlang.org/docs/",
    type: "docs",
    free: true,
    desc: "Official TypeScript docs — type system, utility types, and config guide.",
  },
  {
    areaId: "frontend",
    title: "Vite Docs",
    url: "https://vitejs.dev",
    type: "docs",
    free: true,
    desc: "Official Vite documentation — fast bundler, plugins, SSR configuration.",
  },
];
