import type { Material } from "../../../../domain/constants/materials.js";

export const performanceMaterials: (Material & { areaId: string })[] = [
  {
    areaId: "performance",
    title: "High Performance Browser Networking",
    author: "Ilya Grigorik",
    url: "https://hpbn.co",
    type: "book",
    free: true,
    desc: "TCP, TLS, HTTP/1, HTTP/2, WebSocket, and WebRTC — understanding the network is understanding performance.",
  },
  {
    areaId: "performance",
    title: "Web Performance in Action",
    author: "Jeremy Wagner",
    url: "https://www.manning.com/books/web-performance-in-action",
    type: "book",
    desc: "Practical guide to optimizing page load, assets, fonts, and perceived performance.",
  },
  {
    areaId: "performance",
    title: "web.dev — Performance",
    url: "https://web.dev/performance/",
    type: "docs",
    free: true,
    desc: "Google's structured guide to Core Web Vitals, LCP, FID, CLS — measuring and improving performance.",
  },
  {
    areaId: "performance",
    title: "Chrome DevTools — Performance",
    url: "https://developer.chrome.com/docs/devtools/performance/",
    type: "docs",
    free: true,
    desc: "How to profile, record, and analyze runtime performance using Chrome's built-in tools.",
  },
  {
    areaId: "performance",
    title: "Lighthouse",
    url: "https://developer.chrome.com/docs/lighthouse/",
    type: "tool",
    free: true,
    desc: "Automated auditing for performance, accessibility, SEO, and PWA — built into Chrome.",
  },
  {
    areaId: "performance",
    title: "WebPageTest",
    url: "https://www.webpagetest.org",
    type: "tool",
    free: true,
    desc: "Real-browser performance testing with waterfall charts, filmstrips, and detailed diagnostics.",
  },
  {
    areaId: "performance",
    title: "Bundlephobia",
    url: "https://bundlephobia.com",
    type: "tool",
    free: true,
    desc: "Check the cost of adding any npm package — size, download time, and tree-shaking support.",
  },
  {
    areaId: "performance",
    title: "Systems Performance",
    author: "Brendan Gregg",
    url: "https://www.brendangregg.com/systems-performance.html",
    type: "book",
    desc: "The definitive book on OS and application performance — profiling, tracing, and tuning at every layer.",
  },
  {
    areaId: "performance",
    title: "Designing for Performance",
    author: "Lara Hogan",
    url: "https://larahogan.me/design/",
    type: "book",
    free: true,
    desc: "Performance as a design decision — how visuals, fonts, and layout choices affect load time.",
  },
];
