import type { Material } from "../../../../domain/constants/materials.js";

export const securityMaterials: (Material & { areaId: string })[] = [
  {
    areaId: "security",
    title: "OWASP Top 10",
    url: "https://owasp.org/www-project-top-ten/",
    type: "docs",
    free: true,
    desc: "The most critical web application security risks — injections, broken auth, SSRF, and more.",
  },
  {
    areaId: "security",
    title: "The Web Application Hacker's Handbook",
    author: "Stuttard & Pinto",
    url: "https://www.wiley.com/en-us/The+Web+Application+Hacker%27s+Handbook-p-9781118026472",
    type: "book",
    desc: "Comprehensive attacker-perspective guide to finding and exploiting web vulnerabilities.",
  },
  {
    areaId: "security",
    title: "OWASP Cheat Sheet Series",
    url: "https://cheatsheetseries.owasp.org",
    type: "docs",
    free: true,
    desc: "Actionable, concise cheat sheets on authentication, XSS, SQL injection, CSRF, and 60+ more topics.",
  },
  {
    areaId: "security",
    title: "Hacking: The Art of Exploitation",
    author: "Jon Erickson",
    url: "https://nostarch.com/hacking2.htm",
    type: "book",
    desc: "Low-level exploitation — buffer overflows, shellcode, and understanding the attacker mindset.",
  },
  {
    areaId: "security",
    title: "PortSwigger Web Security Academy",
    url: "https://portswigger.net/web-security",
    type: "course",
    free: true,
    desc: "Free, hands-on labs covering every major web vulnerability class — built by the Burp Suite team.",
  },
  {
    areaId: "security",
    title: "Cryptography I — Coursera",
    author: "Dan Boneh",
    url: "https://www.coursera.org/learn/crypto",
    type: "course",
    free: true,
    desc: "Stanford's rigorous cryptography course — block ciphers, MACs, public-key crypto, and TLS.",
  },
  {
    areaId: "security",
    title: "TryHackMe",
    url: "https://tryhackme.com",
    type: "tool",
    desc: "Gamified cyber security learning with browser-based VMs — beginner to advanced paths.",
  },
  {
    areaId: "security",
    title: "HackTheBox",
    url: "https://www.hackthebox.com",
    type: "tool",
    desc: "Advanced hands-on hacking labs and CTF challenges for sharpening penetration testing skills.",
  },
  {
    areaId: "security",
    title: "Secure by Design",
    author: "Johnsen, Deogun, Sawano",
    url: "https://www.manning.com/books/secure-by-design",
    type: "book",
    desc: "How to embed security into the software design process — domain modeling, avoiding dangerous primitives.",
  },
];
