import type { Material } from "../../../../domain/constants/materials.js";

export const solidMaterials: (Material & { areaId: string })[] = [
  {
    areaId: "solid",
    title: "Clean Code",
    author: "Robert C. Martin",
    url: "https://www.oreilly.com/library/view/clean-code-a/9780136083238/",
    type: "book",
    desc: "The most influential book on writing clean, readable code — naming, functions, classes, and boundaries.",
  },
  {
    areaId: "solid",
    title: "SOLID Principles (Oodesign)",
    url: "https://www.oodesign.com/solid-design-principles.html",
    type: "docs",
    free: true,
    desc: "Clear, example-driven explanation of all five SOLID principles with before/after comparisons.",
  },
  {
    areaId: "solid",
    title: "Design Patterns",
    author: "Gang of Four",
    url: "https://refactoring.guru/design-patterns",
    type: "docs",
    free: true,
    desc: "All 23 GoF patterns explained with real-world examples, diagrams, and code in multiple languages.",
  },
  {
    areaId: "solid",
    title: "Head First Design Patterns",
    author: "Freeman & Robson",
    url: "https://www.oreilly.com/library/view/head-first-design/9781492077992/",
    type: "book",
    desc: "The most approachable introduction to design patterns — visual, conversational, and deeply memorable.",
  },
  {
    areaId: "solid",
    title: "Refactoring",
    author: "Martin Fowler",
    url: "https://refactoring.com",
    type: "book",
    desc: "A catalog of 60+ refactoring techniques — when and how to safely improve existing code structure.",
  },
  {
    areaId: "solid",
    title: "SOLID Principles (Coding Interview University)",
    url: "https://github.com/ardalis/SolidSample",
    type: "docs",
    free: true,
    desc: "Code samples showing SOLID violations and their fixes in a step-by-step progression.",
  },
  {
    areaId: "solid",
    title: "Enterprise Integration Patterns",
    author: "Hohpe & Woolf",
    url: "https://www.enterpriseintegrationpatterns.com",
    type: "book",
    desc: "65 patterns for integrating enterprise applications — messaging, routing, transformation.",
  },
  {
    areaId: "solid",
    title: "A Philosophy of Software Design",
    author: "John Ousterhout",
    url: "https://web.stanford.edu/~ouster/cgi-bin/book.php",
    type: "book",
    desc: "Tactical vs. strategic design, deep vs. shallow modules — a fresh perspective on complexity.",
  },
  {
    areaId: "solid",
    title: "Refactoring Guru",
    url: "https://refactoring.guru",
    type: "docs",
    free: true,
    desc: "Interactive catalog of design patterns and code smells with multi-language examples and UML diagrams.",
  },
];
